name: aitebar

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.1'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  flutter_bloc: ^8.1.2
  dio: ^5.0.3
  freezed_annotation: ^2.2.0
  flutter_gen: ^5.2.0
  auto_route: ^6.0.5
  get_it: ^7.2.0
  flutter_svg: ^2.0.4
  injectable: ^2.1.0
  equatable: ^2.0.5
  line_icons: ^2.0.1
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.0
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  logger: ^1.3.0
  image_picker: ^0.8.7
  intl: ^0.17.0
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^8.0.0
  shimmer: ^2.0.0

  syncfusion_flutter_datagrid: ^21.1.38

  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_gen_runner: ^5.2.0
  auto_route_generator: ^6.0.3
  injectable_generator: ^2.1.5
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1

  flutter_launcher_icons: ^0.13.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app/app_logo.png"
    background_color: "#179E7C"
    theme_color: "#179E7C"


# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#179E7C"
  image: assets/app/app_logo.png
  color_dark: "#179E7C"
  image_dark: assets/app/app_logo.png

  android_12:
    image: assets/app/app_logo.png
    icon_background_color: "#179E7C"
    image_dark: assets/app/app_logo.png
    icon_background_color_dark: "#179E7C"
#
#  web:
#    image: assets/app/app_logo.png
#    image_dark: assets/app/app_logo.png
#    color_web: "#ffffff"
#    color_dark_web: "#121212"
#
#  ios:
#    image: assets/app/app_icon.png
#    image_dark: assets/app/app_icon.png
#    color_ios: "#ffffff"
#    color_dark_ios: "#121212"

flutter_gen:
  output: lib/gen/
  line_length: 150

flutter:
  uses-material-design: true
  # assets
  assets:
    - assets/app/
    - assets/svg/
    - assets/png/
  # fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
