// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyAYmTtR5NcjCNeoXWqzsjWmBzuh5QHN064',
    appId: '1:601786633072:web:f1d3010e14f8fcaf9e5db5',
    messagingSenderId: '601786633072',
    projectId: 'etibaar-245f3',
    authDomain: 'etibaar-245f3.firebaseapp.com',
    storageBucket: 'etibaar-245f3.appspot.com',
    measurementId: 'G-N3QPVNPVVL',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyBs5vu14bSmE-Kwq7IK8AiDs3HBpqyVoYM',
    appId: '1:601786633072:android:0a8dace30c50f1d09e5db5',
    messagingSenderId: '601786633072',
    projectId: 'etibaar-245f3',
    storageBucket: 'etibaar-245f3.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyDr0wH9Q0bb2PtKWZjlbeRUj3LmtiFUapo',
    appId: '1:601786633072:ios:e0d9a27e79cfe2a59e5db5',
    messagingSenderId: '601786633072',
    projectId: 'etibaar-245f3',
    storageBucket: 'etibaar-245f3.appspot.com',
    iosClientId: '601786633072-o0uaabtauge908odeinpk3qcnb3d6a07.apps.googleusercontent.com',
    iosBundleId: 'com.example.etibaar',
  );
}
